export const recipes = [
  {
    id: 1,
    title: 'Protein Pancakes',
    photo: '/images/placeholder-recipe.jpg',
    ingredients: [
      '2 eggs',
      '1 banana',
      '30g protein powder',
      '1 tsp baking powder',
      'Pinch of salt',
    ],
    description: 'Mash the banana, mix with eggs and protein powder. Cook on a non-stick pan until golden brown.',
    video: 'https://www.youtube.com/embed/placeholder',
    shoppingList: [
      'Eggs',
      'Banana',
      'Protein powder',
      'Baking powder',
      'Salt',
    ],
    macros: {
      protein: 25,
      carbs: 30,
      fat: 7,
      calories: 300,
    },
    tags: ['breakfast', 'quick', 'easy', 'kids-friendly', '400 cals'],
  },
  {
    id: 2,
    title: 'Chicken Salad',
    photo: '/images/placeholder-recipe.jpg',
    ingredients: [
      '100g chicken breast',
      '50g mixed greens',
      '1 tomato',
      '1 tbsp olive oil',
      'Salt and pepper',
    ],
    description: 'Grill the chicken, slice and mix with greens, tomato, and olive oil. Season to taste.',
    video: 'https://www.youtube.com/embed/placeholder',
    shoppingList: [
      'Chicken breast',
      'Mixed greens',
      'Tomato',
      'Olive oil',
      'Salt',
      'Pepper',
    ],
    macros: {
      protein: 30,
      carbs: 8,
      fat: 12,
      calories: 280,
    },
    tags: ['lunch', 'quick', 'easy', '200cals'],
  },
];